### ISSUE TITLE
LogicalException

### ISSUE THREAD

**Issue by borhani-vahid** [IPeCompany/SmsPanelV2.dotNet#15]
ظاهرا کلاس LogicalException به صورت internal تعریف شده و امکان catch کردن را ندارد. در صورت امکان public شود و یا همه پیام ها را از طریق مقدار بازگشتی متد (SmsIrResult) ارائه دهد.
- بطور کلی بهتر است پیام ها به زبان انگلیسی باشد حداقل در مورد Exception ها
- و اینکه Exception های internal باید توسط خود شما هندل شوند و اگر لازم است consumer دیگری داشته باشند باید public شوند
با تشکر از زحمات شما

**Comment by SaeedGz98** [comment]
> ظاهرا کلاس LogicalException به صورت internal تعریف شده و امکان catch کردن را ندارد. در صورت امکان public شود و یا همه پیام ها را از طریق مقدار بازگشتی متد (SmsIrResult) ارائه دهد.
> 
> * بطور کلی بهتر است پیام ها به زبان انگلیسی باشد حداقل در مورد Exception ها
> * و اینکه Exception های internal باید توسط خود شما هندل شوند و اگر لازم است consumer دیگری داشته باشند باید public شوند
>   با تشکر از زحمات شما

باعرض سلام، مشکل مرتبط با سطح دسترسی Exception ها برطرف گردید. 
از توجه و همراهی شما بسیار سپاسگزاریم.
